site_name: Smoldyn
nav:
    - Home: index.md
    - Smoldyn User Manual: SmoldynUsersManual.md
    - SmolEmulate : SmolEmulateDoc.md 
    - Smoldyn Code Documentation: SmoldynCodeDoc.md
    - libsmoldyn Manual: LibsmoldynManual.md 
    - Python Bindings: PythonBindings.md

theme: 
    name: material
    highlightjs: true
    features:
        - tabs

repo_url: https://github.com/dilawar/Smoldyn-official

markdown_extensions:
    - smarty
    - sane_lists
    - codehilite
    - admonition
    - tables
    - toc:
        permalink: true

plugins:
    - search
    - pheasant
